### PR TITLE
DuckDuckGo Code Corrected

### PR DESCRIPTION
**Pull request by Ratikant-rout**
Kindly Checkout The Code And If This Works Well Then Kindly Merge The Pull Request @hiteshkumar8642 Thanks For The Project I Really Loved This Project

### CODE REVIEW

**Comment by codewithnick** [comment]
Please attach working screenshots for your changes

**Comment by Ratikant-rout** [comment]
@codewithnick Sure bro am providing the screenshots in a while. But If You Liked my Work Please Merge It Brother😇😇

**Comment by Ratikant-rout** [comment]
Ya @codewithnick brother it's Running Fine I Have Checked Twice. Please Merge It. I My Meeting I will Provide You Screenshots if it not runs on your pc So kindly test it please
Thank You For This Oppertunity😇

**Comment by Ratikant-rout** [comment]
@codewithnick bro am not able to attach the screenshot i think some issues are their in your end?

**Comment by codewithnick** [comment]
hi @Ratikant-rout  the page parameter does not work like you have added in your code
image
please check this,
even after adding page param in the payload i am still getting results of page 1 


try to take up any other issue if you do not understand this

**Comment by Ratikant-rout** [comment]
@codewithnick Let Me Try Once More If This Works Then Well And Good If Not Then I Will Switch To Next Issues

**Comment by codewithnick** [comment]
Sure

**Comment by codewithnick** [comment]
You can open new issues too, for example add new searchengine

**Comment by Ratikant-rout** [comment]
@codewithnick check out the Final commit that might work for your code SHA CODE:- ea4fc14335162677d839fc7b22c5f393f4e0c598

**Comment by Ratikant-rout** [comment]
@codewithnick CheckOut The Final Check Pass Only. SIH CODE:- 099b57879976ef9577e1ab5f58d9113855b5ddd2

**Comment by Ratikant-rout** [comment]
Looking Forward Am Also Trying To Add A Search Engine @codewithnick Thanks For The opportunity.😇

**Comment by Ratikant-rout** [comment]
@codewithnick Thanks For The Appreciation If Possible Kindly Correct The code and merge It. I Am Thinking To Move Towards Making A New Search Engine.

**Pull request closed without merging**
